on:
  push:
    paths:
      - "bio/*"
jobs:
  upsert-bio:
    environment: upsert-bio
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: yarn install
      - run: yarn upsert
        env:
          IDENTIFIER: ${{ vars.identifier }}
          APP_PASSWORD: ${{ secrets.app_password }}
